export const is = [
	"dreaming",
	"campfire dreaming",
	"crying over spilled milk",
	"putting out fires",
	"eating life's lemons",
	"feeling good",
	"trying",
	'moving forwards',
	"taking risks",
	"dying young as late as possible",
	"crossing tees and dotting eyes",
	"out of monster",
	"never gonna give you up",
	"cheese",
	"forgetting something",
	"chasing the sun",
	"jumping for joy",
	"always learning",
	"on a journey",
	"on a roll",
	"doing flips",
	"climbing mountains",
	"playing skate 3",
	"defying gravity",
	"really cool",
	"working hard",
	"setting sail",
	"high on life",
	"geeking out",
	"rocking out",
	"helping out",
	"vibing out",
	"a goofball",
	"touching grass",
	"making friends",
	"making waves",
	"making peace",
	"petting the cat",
	"lost in thought",
	"charting waters",
	"locking in",
	"kickflippin",
	"flying too close to the sun",
	"tempting fate",
	"pushing luck",
	"living",
	"shooting at the stars",
	"wishing on a star",
	"finally free",
	"only going up",
];

export function onRequestGet(context) {
	return new Response("is " + is[Math.floor(Math.random() * is.length)], {
		headers: {
			"Content-Type": "text/plain",
		},
	});
}
